### ISSUE TITLE
Pushing media features to opus-media-recorder

### ISSUE THREAD

**Issue by kbumsik** [CameraKit/webm-media-recorder#7]
Hi,
I'm the maintainer of [opus-media-recorder](https://github.com/kbumsik/opus-media-recorder). I came across this fork and the video recorder features looks amazing. I'm interesting in pulling some video capabilities to opus-media-recorder (I will do it myself, you don't need to do any work.)

I would like to ask you if it is okay to do so. At least I would like to make sure about the license, because LICENSE file doesn't look updated. I would appreciate if you are fine with me pulling the feature under the same MIT license.

Also, how's the performance of video encoding? I decided not to add video encoding feature when I was designing opus-media-encorder at the beginning because I was unsure if it performs well since WebAssembly has a bad performance on SIMD operations yet.

Regards,
Bumsik Kim

**Comment by exPHAT** [comment]
Hello!

There should be no issues with you bringing video capabilities back into `opus-media-recorder`, feel free to use it under the same MIT License.

The video encoding performance is suboptimal currently as the frames are encoded synchronously by the worker. You may want to take a look at https://github.com/GoogleChromeLabs/webm-wasm which could provide some insight on how to do this better. 

@austinkettner any objections?

**Comment by austinkettner** [comment]
Sounds good @exPHAT and @kbumsik

**Comment by kbumsik** [comment]
Thank you, I'll start working on it soon!

**Comment by prateekkaistha** [comment]
Hi @exPHAT,
Great idea to add video capabilities to `opus-media-recorder` by @kbumsik .
How can we start using this to record videos?? Is the integration similar to `opus-media-recorder`, if yes then what changes should be made in integration? Can you please highlight them? 
Thanks.
